## Pandas - Importing data

Please download the following data and move it to an appropriate folder:

- <a href="https://drive.google.com/file/d/1gVDDJg3Ngnz8h9f2pX9AcdgWgx5zkV6U/view?usp=sharing">Bridge Inspections excerpt</a>.

In [1]:
## import the pandas library in this cell
import pandas as pd

### Ingest the following dataset into this note:

In [6]:
## import data and store in dataframe call dfbi (short perhaps for dataframe bridge inspections)
df = pd.read_csv("bridge-inspections-excerpt.csv")

In [7]:
## call the first 10 rows
df.head(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN
7,47,189,'GOOSE CREEK',36033059.0,86040120.0,2.0,8.0,1965.0,2,19.0,N,N,N,6,6,NaN
8,47,189,'BRANCH',36014830.0,86030353.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,6,NaN
9,47,189,'PURTLE CREEK',36004548.0,86023480.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,6,NaN

In [8]:
## call the last 5 rows
df.tail(5)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [9]:
## call a 20 random rows
df.sample(20)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
9016,48,439,'TIMBER CREEK',32402427.0,97273638.0,4.0,19.0,1985.0,1,19.0,N,N,N,7,6,NaN
4360,48,223,'ELM CREEK',33014490.0,95413077.0,1.0,2.0,1942.0,1,4.0,7,7,6,6,N,NaN
3607,48,147,'PEPPERCAMP CREEK',33464175.0,96083705.0,2.0,9.0,1990.0,3,2.0,7,6,6,6,N,NaN
33709,48,453,'COLORADO RIVER',30205895.0,97474903.0,1.0,14.0,1983.0,3,12.0,5,6,5,6,N,NaN
99025,53,27,'WEST FORK HOQUIAM RIVER',47032550.0,123554030.0,2.0,9.0,1976.0,2,1.0,7,7,7,8,N,NaN
17971,48,145,'PERRY CREEK',31144193.0,96580573.0,1.0,7.0,1960.0,1,2.0,7,7,7,6,N,NaN
91101,51,13,'EBL RT 27#1034 & RDW B&F',38515336.0,77040687.0,NaN,14.0,1942.0,3,2.0,NaN,NaN,NaN,NaN,NaN,NaN
66338,48,355,'SH 44',NaN,NaN,NaN,17.0,2022.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
80606,51,75,'Beaverdam Creek',37404034.0,77500933.0,1.0,8.0,1986.0,1,19.0,N,N,N,6,6,NaN
93314,51,59,'ALBAN-BACKLICK & RAMP GG',38443584.0,77112266.0,NaN,19.0,1993.0,3,2.0,NaN,NaN,NaN,NaN,NaN,NaN
58957,48,155,'NORTH BEAVER CREEK',33585767.0,99371623.0,1.0,6.0,1929.0,1,19.0,N,N,N,7,6,NaN
62308,48,217,'IH 35',32003162.0,97054217.0,NaN,11.0,2001.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
18468,48,217,'BYNUM CREEK RELIEF',31553185.0,96532672.0,1.0,7.0,1952.0,1,1.0,7,7,7,6,N,NaN
83590,51,163,'RTE I 64',37514708.0,79293074.0,1.0,9.0,1977.0,4,2.0,7,6,5,N,N,NaN
56981,48,333,'FARMERS CREEK',31331921.0,98400148.0,1.0,7.0,1940.0,8,19.0,N,N,N,6,7,NaN
38998,48,163,'Draw',28551017.0,99061775.0,1.0,11.0,1973.0,1,19.0,N,N,N,7,7,NaN
54811,48,505,'Arroyo San Francisco',27045739.0,99253947.0,1.0,2.0,1934.0,1,4.0,7,7,6,7,N,NaN
7497,48,439,'SH 199',32520102.0,97312624.0,1.0,14.0,2011.0,5,2.0,7,7,7,N,N,NaN
21146,48,423,'LONG BRAKE CR',32280246.0,95260953.0,32.0,6.0,2013.0,1,19.0,N,N,N,7,7,NaN
93884,51,15,'ROUTE 11 NBL & SBL',38071371.0,79035832.0,NaN,12.0,2001.0,4,2.0,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there

df.info()

## there are 15 columns and 100_000 rows, and the data includes integers, strings and decimals

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   STATE_CODE_001           100000 non-null  int64
 1   COUNTY_CODE_003          100000 non-null  int64
 2   FEATURES_DESC_006A       100000 non-null  str
 3   LAT_016                  99493 non-null   float64
 4   LONG_017                 99486 non-null   float64
 5   OWNER_022                82621 non-null   float64
 6   FUNCTIONAL_CLASS_026     99660 non-null   float64
 7   YEAR_BUILT_027           99997 non-null   float64
 8   STRUCTURE_KIND_043A      100000 non-null  int64
 9   STRUCTURE_TYPE_043B      99999 non-null   float64
 10  DECK_COND_058            82621 non-null   str
 11  SUPERSTRUCTURE_COND_059  82621 non-null   str
 12  SUBSTRUCTURE_COND_060    82621 non-null   str
 13  CHANNEL_COND_061         82621 non-null   str
 14  CULVERT_COND_062         82621 non-null   str
 15  PIER_PROTECTION_111      4353 non-null    float64
dtypes: float64(7), int64(3), str(6)
memory usage: 12.2 MB

### Which column has the most missing data...just a quick estimate?

In [ ]:
## column 15 has the most missing data, it only has 4_000ish non-null cells

In [12]:
## call the top 7 rows
df.head(7)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN

In [13]:
## call a sample of 10
df.sample(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
14451,48,385,'WEST FRIO RIVER',29443950.0,99451041.0,1.0,6.0,1958.0,5,2.0,7,7,6,5,N,NaN
32173,48,481,'MOTT SLOUGH',29185335.0,96205991.0,2.0,9.0,1987.0,7,2.0,6,7,6,8,N,NaN
34499,48,453,'BRANCH OF WALNUT CREEK',30163235.0,97383800.0,2.0,9.0,1980.0,1,19.0,N,N,N,7,6,NaN
48284,48,121,'KSC Railroad',33120765.0,97095294.0,1.0,11.0,1970.0,5,2.0,7,7,6,N,N,NaN
73207,49,35,'SR-175 11400 SO. ST.',40323823.0,111534029.0,NaN,14.0,2010.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
9919,48,9,'PECAN CREEK RELIEF',33485385.0,98345701.0,2.0,9.0,1987.0,1,19.0,N,N,N,7,7,NaN
53251,48,291,'US 90 & UPRR',30002928.0,94561983.0,1.0,12.0,2021.0,5,2.0,8,8,8,7,N,NaN
13221,48,371,'DRAW',30524985.0,102534964.0,1.0,6.0,1936.0,1,19.0,N,N,N,6,7,NaN
97157,53,57,'SKY CREEK',48374866.0,121194034.0,1.0,6.0,1989.0,5,4.0,7,7,7,8,N,NaN
32599,48,53,'BEAVER CREEK',30521752.0,98241278.0,1.0,7.0,1967.0,1,2.0,7,7,7,7,N,NaN

In [14]:
## call the bottom 6
df.tail(6)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99994,53,61,'SWAMP CREEK',47482979.0,122152176.0,2.0,16.0,1963.0,1,22.0,7,7,5,6,N,NaN
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [17]:
## call the year built column using dot notation
df.YEAR_BUILT_027

0        1965.0
1        1930.0
2        1935.0
3        1960.0
4        1970.0
          ...
99995    1956.0
99996    1960.0
99997    1965.0
99998    1981.0
99999    1963.0
Name: YEAR_BUILT_027, Length: 100000, dtype: float64

In [18]:
## call FEATURES_DESC_006A as a series using square bracket notation

df["FEATURES_DESC_006A"]

0                          'BRANCH'
1                          'BRANCH'
2                          'BRANCH'
3                        'OVERFLOW'
4                 'HURRICANE CREEK'
                    ...
99995                 'TROUT CREEK'
99996              'COLVILLE RIVER'
99997                       'DRAIN'
99998                 'LEACH CREEK'
99999    'SOUTH FORK PALOUSE RIVER'
Name: FEATURES_DESC_006A, Length: 100000, dtype: str

In [19]:
## what are the unique owner codes?
df["OWNER_022"].unique()

array([ 2.,  4.,  1.,  3., 79., 63., 67., 64., 70., 66., 72., 74., nan,
       68., 21., 80., 31., 32., 11., 40., 25., 26., 75., 12., 27., 55.,
       56., 69., 62., 73., 76., 54., 77.])

### What do these codes mean?

In [ ]:
## they stand for the number of owners ?